import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "collectibles Showcase",
  description: "Generated by create next app",
};

// some minor changes to the layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-mono antialiased bg-slate-900`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
